### ISSUE TITLE
Cannot proceed infence with project official samoe 

### ISSUE THREAD

**Issue by leonialla** [Srameo/DNF#7]
When I try to use `demos/images_process.sh` to reason about the official example data of this project <https://github.com/Srameo/DNF/blob/main/docs/demo.md#provided-data>, it says
> rawpy._rawpy.LibRawFileUnsupportedError: b'Unsupported file format or not RAW file'

Running environment. 
- Ubuntu 16.04 LTS 
- Python 3.10
- CUDA 11.7
- Pytorch 2.0.1+cu117

Screenshot of error message:
<img width="1251" alt="image" src="https://github.com/Srameo/DNF/assets/88543173/73c0e979-39f1-4001-8c65-8b510f9597b7">

**Comment by Srameo** [comment]
It seems that our script is encountering an issue while reading the data. Could you please show us the data format you would like us to process? 

By the way, we strongly recommend following our Readme for environment setup. We are unsure if our code supports your current environment, especially PyTorch 2.0.

**Comment by GaoTianWL** [comment]
ERROR: Exception:
Traceback (most recent call last):
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 503, in run
    pycompile=options.compile,
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 81, in install_given_reqs
    pycompile=pycompile,
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 800, in install
    requested=self.user_supplied,
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/pip/_internal/operations/install/wheel.py", line 737, in install_wheel
    requested=requested,
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/pip/_internal/operations/install/wheel.py", line 589, in _install_wheel
    file.save()
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/pip/_internal/operations/install/wheel.py", line 388, in save
    shutil.copyfileobj(f, dest)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/shutil.py", line 79, in copyfileobj
    buf = fsrc.read(length)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/zipfile.py", line 930, in read
    data = self._read1(n)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/zipfile.py", line 1020, in _read1
    self._update_crc(data)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/zipfile.py", line 948, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'caffe2/python/caffe2_pybind11_state_gpu.cpython-37m-x86_64-linux-gnu.so'
这是什么原因呢

**Comment by Srameo** [comment]
您好，不知道您可否提供一下您的开发环境信息以及复现该bug的命令？

**Comment by GaoTianWL** [comment]
Traceback (most recent call last):
  File "runner.py", line 324, in <module>
    main(config)
  File "runner.py", line 39, in main
    profile_model(config, profile_forward, model, train_dataloader, logger)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "runner.py", line 106, in profile_model
    data = next(data_iter)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/vipsl416-3-tiangao/lowlight/DNF-main/datasets/SID_dict_dataset.py", line 119, in __getitem__
    clean_rgb = np.load(os.path.join(self.data_path, lbl_file.replace('long', 'long_post_int')+'.npy'), allow_pickle=True)
  File "/home/vipsl416-3-tiangao/anaconda3/envs/dnf/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/Sony/./Sony/long_post_int/00119_00_30s.ARW.npy'
您好，上面那个问题解决了。下载了预训练节点之后，运行了bash benchmarks/sid_sony.sh pretrained/model_best_sid_sony.pth --save-image  在base.yml文件中也修改了数据集路径，数据集也转换成数组形式进行加速，但是还是报错了。
